version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
      args:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PW=${POSTGRES_PW}
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_DB=${POSTGRES_DB}
    environment:
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PW=${POSTGRES_PW}
    - POSTGRES_URL=${POSTGRES_URL}
    - POSTGRES_DB=${POSTGRES_DB}
    image: react-flask-app-api
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
      - REACT_APP_AUTH0_DOMAIN=${REACT_APP_AUTH0_DOMAIN}
      - REACT_APP_AUTH0_CLIENT_ID=${REACT_APP_AUTH0_CLIENT_ID}
    environment:
    - REACT_APP_AUTH0_DOMAIN=${REACT_APP_AUTH0_DOMAIN}
    - REACT_APP_AUTH0_CLIENT_ID=${REACT_APP_AUTH0_CLIENT_ID}
    image: react-flask-app-client
    ports:
      - "5000:5000"