"""Initial commit

Revision ID: 1c1a064d7368
Revises: 
Create Date: 2021-08-19 10:41:33.489373

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1c1a064d7368'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('auth_id', sa.String(length=128), nullable=False),
    sa.Column('given_name', sa.String(length=256), nullable=True),
    sa.Column('family_name', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('first_login', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_id')
    )
    op.create_table('projects',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('project_name', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('project_id', postgresql.UUID(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('recording_start', sa.DateTime(), nullable=False),
    sa.Column('recording_stop', sa.DateTime(), nullable=False),
    sa.Column('video_location', sa.String(length=32), nullable=True),
    sa.Column('transcript_location', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('note_id', postgresql.UUID(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('time', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('notes')
    op.drop_table('projects')
    op.drop_table('users')
    # ### end Alembic commands ###
