"""Change transcription status to int

Revision ID: 839a2b222fe5
Revises: 0845b119abe9
Create Date: 2021-08-23 10:12:54.017419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '839a2b222fe5'
down_revision = '0845b119abe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('transcription_status', sa.Integer(), nullable=True))
    op.drop_column('notes', 'transcripted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('transcripted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('notes', 'transcription_status')
    # ### end Alembic commands ###
